const CANDIDATE_ACTIONS = {
    CREATE_CANDIDATE: 'CREATE_CANDIDATE',
    LOAD_CANDIDATES: 'LOAD_CANDIDATES',
    LOAD_CANDIDATE: 'LOAD_CANDIDATE',
    UPDATE_CANDIDATE: 'UPDATE_CANDIDATE',
    DELETE_CANDIDATE: 'DELETE_CANDIDATE'
}

export default CANDIDATE_ACTIONS;