const PROJECT_ACTIONS = {
    ADD_PROJECT: 'ADD_PROJECT',
    UPDATE_PROJECT_DETAILS: 'UPDATE_PROJECT_DETAILS',
    DELETE_PROJECT: 'DELETE_PROJECT',
    LOAD_PROJECTS: 'LOAD_PROJECTS'
}

export default PROJECT_ACTIONS;